[workspace]
resolver = "3"
members = [
    "crates/domain",
    "crates/console",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
domain = { path = "crates/domain" }
console = { path = "crates/console" }
serde = { version = "1.0.229", features = ["derive"] }
rand = "0.10.3"
serde_json = "1.0.151"
chrono = "0.4.45"
